# Prodigal Son

legacy_standard_bible = """
Jesus continued: “There was a man who had two sons. The younger one said to his father, ‘Father, give me my share of the estate.’ So he divided his property between them.
“Not long after that, the younger son got together all he had, set off for a distant country and there squandered his wealth in wild living. After he had spent everything, there was a severe famine in that whole country, and he began to be in need. So he went and hired himself out to a citizen of that country, who sent him to his fields to feed pigs. He longed to fill his stomach with the pods that the pigs were eating, but no one gave him anything. “When he came to his senses, he said, ‘How many of my father’s hired servants have food to spare, and here I am starving to death!  I will set out and go back to my father and say to him: Father, I have sinned against heaven and against you. I am no longer worthy to be called your son; make me like one of your hired servants.’ So he got up and went to his father.
“But while he was still a long way off, his father saw him and was filled with compassion for him; he ran to his son, threw his arms around him and kissed him.
 “The son said to him, ‘Father, I have sinned against heaven and against you. I am no longer worthy to be called your son.’
 “But the father said to his servants, ‘Quick! Bring the best robe and put it on him. Put a ring on his finger and sandals on his feet.  Bring the fattened calf and kill it. Let’s have a feast and celebrate.  For this son of mine was dead and is alive again; he was lost and is found.’ So they began to celebrate.
 “Meanwhile, the older son was in the field. When he came near the house, he heard music and dancing.  So he called one of the servants and asked him what was going on.  ‘Your brother has come,’ he replied, ‘and your father has killed the fattened calf because he has him back safe and sound.’
 “The older brother became angry and refused to go in. So his father went out and pleaded with him.  But he answered his father, ‘Look! All these years I’ve been slaving for you and never disobeyed your orders. Yet you never gave me even a young goat so I could celebrate with my friends. But when this son of yours who has squandered your property with prostitutes comes home, you kill the fattened calf for him!’
 “‘My son,’ the father said, ‘you are always with me, and everything I have is yours. 32 But we had to celebrate and be glad, because this brother of yours was dead and is alive again; he was lost and is found.’”
"""
king_james_version = """
And he said, A certain man had two sons: And the younger of them said to his father, Father, give me the portion of goods that falleth to me. And he divided unto them his living. And not many days after the younger son gathered all together, and took his journey into a far country, and there wasted his substance with riotous living. And when he had spent all, there arose a mighty famine in that land; and he began to be in want. And he went and joined himself to a citizen of that country; and he sent him into his fields to feed swine. And he would fain have filled his belly with the husks that the swine did eat: and no man gave unto him. And when he came to himself, he said, How many hired servants of my father's have bread enough and to spare, and I perish with hunger!  I will arise and go to my father, and will say unto him, Father, I have sinned against heaven, and before thee,  And am no more worthy to be called thy son: make me as one of thy hired servants. And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed h And the son said unto him, Father, I have sinned against heaven, and in thy sight, and am no more worthy to be called thy son.  But the father said to his servants, Bring forth the best robe, and put it on him; and put a ring on his hand, and shoes on his feet: And bring hither the fatted calf, and kill it; and let us eat, and be merry: For this my son was dead, and is alive again; he was lost, and is found. And they began to be merry.
Now his elder son was in the field: and as he came and drew nigh to the house, he heard musick and dancing. And he called one of the servants, and asked what these things meant.  And he said unto him, Thy brother is come; and thy father hath killed the fatted calf, because he hath received him safe and sound. And he was angry, and would not go in: therefore came his father out, and intreated him. And he answering said to his father, Lo, these many years do I serve thee, neither transgressed I at any time thy commandment: and yet thou never gavest me a kid, that I might make merry with my friends:  But as soon as this thy son was come, which hath devoured thy living with harlots, thou hast killed for him the fatted calf. And he said unto him, Son, thou art ever with me, and all that I have is thine. It was meet that we should make merry, and be glad: for this thy brother was dead, and is alive again; and was lost, and is found.
"""
new_international_version = """
Jesus continued: “There was a man who had two sons. The younger one said to his father, ‘Father, give me my share of the estate.’ So he divided his property between them.
“Not long after that, the younger son got together all he had, set off for a distant country and there squandered his wealth in wild living. After he had spent everything, there was a severe famine in that whole country, and he began to be in need. So he went and hired himself out to a citizen of that country, who sent him to his fields to feed pigs. He longed to fill his stomach with the pods that the pigs were eating, but no one gave him anything.
“When he came to his senses, he said, ‘How many of my father’s hired servants have food to spare, and here I am starving to death! I will set out and go back to my father and say to him: Father, I have sinned against heaven and against you. I am no longer worthy to be called your son; make me like one of your hired servants.’ So he got up and went to his father.
“But while he was still a long way off, his father saw him and was filled with compassion for him; he ran to his son, threw his arms around him and kissed him.
“The son said to him, ‘Father, I have sinned against heaven and against you. I am no longer worthy to be called your son.’
“But the father said to his servants, ‘Quick! Bring the best robe and put it on him. Put a ring on his finger and sandals on his feet. Bring the fattened calf and kill it. Let’s have a feast and celebrate. For this son of mine was dead and is alive again; he was lost and is found.’ So they began to celebrate.
“Meanwhile, the older son was in the field. When he came near the house, he heard music and dancing. So he called one of the servants and asked him what was going on. ‘Your brother has come,’ he replied, ‘and your father has killed the fattened calf because he has him back safe and sound.’
“The older brother became angry and refused to go in. So his father went out and pleaded with him. But he answered his father, ‘Look! All these years I’ve been slaving for you and never disobeyed your orders. Yet you never gave me even a young goat so I could celebrate with my friends. But when this son of yours who has squandered your property with prostitutes comes home, you kill the fattened calf for him!’
“ ‘My son,’ the father said, ‘you are always with me, and everything I have is yours. But we had to celebrate and be glad, because this brother of yours was dead and is alive again; he was lost and is found.’ ”
"""
english_standard_version = """
And he said, “There was a man who had two sons. And the younger of them said to his father, ‘Father, give me the share of property that is coming to me.’ And he divided his property between them.
Not many days later, the younger son gathered all he had and took a journey into a far country, and there he squandered his property in reckless living. And when he had spent everything, a severe famine arose in that country, and he began to be in need. So he went and hired himself out to one of the citizens of that country, who sent him into his fields to feed pigs. And he was longing to be fed with the pods that the pigs ate, and no one gave him anything.
But when he came to himself, he said, ‘How many of my father’s hired servants have more than enough bread, but I perish here with hunger! I will arise and go to my father, and I will say to him, “Father, I have sinned against heaven and before you. I am no longer worthy to be called your son. Treat me as one of your hired servants.”’
And he arose and came to his father. But while he was still a long way off, his father saw him and felt compassion, and ran and embraced him and kissed him. And the son said to him, ‘Father, I have sinned against heaven and before you. I am no longer worthy to be called your son.’
But the father said to his servants, ‘Bring quickly the best robe, and put it on him, and put a ring on his hand, and shoes on his feet. And bring the fattened calf and kill it, and let us eat and celebrate. For this my son was dead, and is alive again; he was lost, and is found.’ And they began to celebrate.
Now his older son was in the field. And as he came and drew near to the house, he heard music and dancing. And he called one of the servants and asked what these things meant. And he said to him, ‘Your brother has come, and your father has killed the fattened calf, because he has received him back safe and sound.’
But he was angry and refused to go in. His father came out and entreated him, but he answered his father, ‘Look, these many years I have served you, and I never disobeyed your command, yet you never gave me a young goat, that I might celebrate with my friends. But when this son of yours came, who has devoured your property with prostitutes, you killed the fattened calf for him!’
And he said to him, ‘Son, you are always with me, and all that is mine is yours. It was fitting to celebrate and be glad, for this your brother was dead, and is alive; he was lost, and is found.’”
"""
new_living_translation = """
Jesus continued: “There was a man who had two sons. The younger son told his father, ‘I want my share of your estate now before you die.’ So his father agreed to divide his wealth between his sons.
A few days later this younger son packed all his belongings and moved to a distant land, and there he wasted all his money in wild living. About the time his money ran out, a great famine swept over the land, and he began to starve. He persuaded a local farmer to hire him, and the man sent him into his fields to feed the pigs. The young man became so hungry that even the pods he was feeding the pigs looked good to him. But no one gave him anything.
When he finally came to his senses, he said to himself, ‘At home even the hired servants have food enough to spare, and here I am dying of hunger! I will go home to my father and say, “Father, I have sinned against both heaven and you, and I am no longer worthy of being called your son. Please take me on as a hired servant.”’
So he returned home to his father. And while he was still a long distance away, his father saw him coming. Filled with love and compassion, he ran to his son, embraced him, and kissed him.
His son said to him, ‘Father, I have sinned against both heaven and you, and I am no longer worthy of being called your son.’
But his father said to the servants, ‘Quick! Bring the finest robe in the house and put it on him. Get a ring for his finger and sandals for his feet. And kill the calf we have been fattening. We must celebrate with a feast, for this son of mine was dead and has now returned to life. He was lost, but now he is found.’ So the party began.
Meanwhile, the older son was in the fields working. When he returned home, he heard music and dancing in the house, and he asked one of the servants what was going on. The servant replied, ‘Your brother is back, and your father has killed the fattened calf. We are celebrating because of his safe return.’
The older brother was angry and wouldn’t go in. His father came out and begged him, but he replied, ‘All these years I’ve slaved for you and never once refused to do a single thing you told me to. And in all that time you never gave me even one young goat for a feast with my friends. Yet when this son of yours comes back after squandering your money on prostitutes, you celebrate by killing the fattened calf!’
His father said to him, ‘Look, dear son, you have always stayed by me, and everything I have is yours. We had to celebrate this happy day. For your brother was dead and has come back to life. He was lost, but now he is found.’”
"""
new_american_standard_bible = """
And He said, “A man had two sons. The younger of them said to his father, ‘Father, give me the share of the estate that falls to me.’ So he divided his wealth between them. And not many days later, the younger son gathered everything together and went on a journey into a distant country, and there he squandered his estate with loose living. Now when he had spent everything, a severe famine occurred in that country, and he began to be impoverished. So he went and hired himself out to one of the citizens of that country, and he sent him into his fields to feed swine. And he would have gladly filled his stomach with the pods that the swine were eating, and no one was giving anything to him. But when he came to his senses, he said, ‘How many of my father’s hired men have more than enough bread, but I am dying here with hunger! I will get up and go to my father, and I will say to him, “Father, I have sinned against heaven, and in your sight; I am no longer worthy to be called your son; make me as one of your hired men.”’ So he got up and came to his father. But while he was still a long way off, his father saw him and felt compassion for him, and ran and embraced him and kissed him. And the son said to him, ‘Father, I have sinned against heaven and in your sight; I am no longer worthy to be called your son.’ But the father said to his slaves, ‘Quickly bring out the best robe and put it on him, and put a ring on his hand and sandals on his feet; and bring the fattened calf, kill it, and let us eat and be merry; for this son of mine was dead and has come to life again; he was lost and has been found.’ And they began to be merry.
Now his older son was in the field, and when he came and approached the house, he heard music and dancing. And he summoned one of the servants and began inquiring what these things could be. And he said to him, ‘Your brother has come, and your father has killed the fattened calf because he has received him back safe and sound.’ But he became angry and was not willing to go in; and his father came out and began pleading with him. But he answered and said to his father, ‘Look! For so many years I have been serving you and I have never neglected a command of yours, and yet you have never given me a young goat so that I might celebrate with my friends; but when this son of yours came, who has devoured your wealth with prostitutes, you killed the fattened calf for him.’ And he said to him, ‘Son, you have always been with me, and all that is mine is yours. But we had to celebrate and rejoice, for this brother of yours was dead and has begun to live, and was lost and has been found.’”
"""
new_king_james_version = """
Then He said: “A certain man had two sons. And the younger of them said to his father, ‘Father, give me the portion of goods that falls to me.’ So he divided to them his livelihood. And not many days after, the younger son gathered all together, journeyed to a far country, and there wasted his possessions with prodigal living. But when he had spent all, there arose a severe famine in that land, and he began to be in want. Then he went and joined himself to a citizen of that country, and he sent him into his fields to feed swine. And he would gladly have filled his stomach with the pods that the swine ate, and no one gave him anything.
“But when he came to himself, he said, ‘How many of my father’s hired servants have bread enough and to spare, and I perish with hunger! I will arise and go to my father, and will say to him, Father, I have sinned against heaven and before you, and I am no longer worthy to be called your son. Make me like one of your hired servants.’
“And he arose and came to his father. But when he was still a great way off, his father saw him and had compassion, and ran and fell on his neck and kissed him. And the son said to him, ‘Father, I have sinned against heaven and in your sight, and am no longer worthy to be called your son.’
“But the father said to his servants, ‘Bring out the best robe and put it on him, and put a ring on his hand and sandals on his feet. And bring the fatted calf here and kill it, and let us eat and be merry; for this my son was dead and is alive again; he was lost and is found.’ And they began to be merry.
“Now his older son was in the field. And as he came and drew near to the house, he heard music and dancing. So he called one of the servants and asked what these things meant. And he said to him, ‘Your brother has come; and because he has received him safe and sound, your father has killed the fatted calf.’
“But he was angry and would not go in. Therefore his father came out and pleaded with him. So he answered and said to his father, ‘Lo, these many years I have been serving you; I never transgressed your commandment at any time; and yet you never gave me a young goat that I might make merry with my friends. But as soon as this son of yours came, who has devoured your livelihood with harlots, you killed the fatted calf for him.’
“And he said to him, ‘Son, you are always with me, and all that I have is yours. It was right that we should make merry and be glad, for your brother was dead and is alive again, and was lost and is found.’”
"""
christian_standard_bible = """
Jesus also said, “A man had two sons. The younger of them said to his father, ‘Father, give me the share of the estate I have coming to me.’ So he distributed the assets to them.
Not many days later, the younger son gathered together all he had and traveled to a distant country where he squandered his estate in foolish living. After he had spent everything, a severe famine struck that country, and he had nothing. Then he went to work for one of the citizens of that country, who sent him into his fields to feed pigs. He longed to eat his fill from the pods that the pigs were eating, but no one would give him any.
When he came to his senses, he said, ‘How many of my father’s hired workers have more than enough food, and here I am dying of hunger! I’ll get up, go to my father, and say to him, Father, I have sinned against heaven and in your sight. I’m no longer worthy to be called your son. Make me like one of your hired workers.’
So he got up and went to his father. But while the son was still a long way off, his father saw him and was filled with compassion. He ran through his arms around his neck and kissed him.
The son said to him, ‘Father, I have sinned against heaven and in your sight. I’m no longer worthy to be called your son.’
But the father told his servants, ‘Quick! Bring out the best robe and put it on him; put a ring on his finger and sandals on his feet. Then bring the fattened calf and slaughter it, and let’s celebrate with a feast, because this son of mine was dead and is alive again; he was lost and is found.’ So they began to celebrate.
Now his older son was in the field. As he came near the house, he heard music and dancing. So he summoned one of the servants and asked what these things meant. ‘Your brother is here,’ he told him, ‘and your father has slaughtered the fattened calf because he has him back safe and sound.’
Then he became angry and didn’t want to go in. So his father came out and pleaded with him. But he replied to his father, ‘Look, I’ve been slaving many years for you and I’ve never disobeyed your orders; yet you never gave me a goat so I could celebrate with my friends. But when this son of yours came, who has devoured your assets with prostitutes, you slaughtered the fattened calf for him.’
‘Son,’ he said to him, ‘you are always with me, and everything I have is yours. But we had to celebrate and rejoice, because this brother of yours was dead and is alive again; he was lost and is found.’”
"""
new_english_translation = """
Jesus continued, “There was a man who had two sons. The younger son said to his father, ‘Father, give me the share of the estate that will belong to me.’ So he divided his assets between them.
A few days later, the younger son gathered together all he had and traveled to a distant country, where he squandered his wealth in wild living. Then, after he had spent everything, a severe famine took place in that country, and he began to be in need. So he went and hired himself out to one of the citizens of that country, who sent him to his fields to feed pigs. He was longing to eat the pods that the pigs were eating, but no one gave him anything.
But when he came to his senses, he said, ‘How many of my father’s hired servants have food to spare, but here I am dying from hunger! I will get up and go to my father, and I will say to him, “Father, I have sinned against heaven and against you. I am no longer worthy to be called your son; treat me like one of your hired servants.”’
So he got up and went to his father. But while he was still a long way from home, his father saw him and was filled with compassion. He ran and hugged his son and kissed him. Then his son said to him, ‘Father, I have sinned against heaven and against you. I am no longer worthy to be called your son.’
But the father said to his servants, ‘Quick! Bring out the best robe and put it on him. Put a ring on his finger and sandals on his feet. Bring the fattened calf and kill it. Let us eat and celebrate, because this son of mine was dead and is alive again; he was lost and is found!’ So they began to celebrate.
Now his older son was in the field. As he came and approached the house, he heard music and dancing. So he called one of the servants and asked what was happening. The servant replied, ‘Your brother has returned, and your father has killed the fattened calf because he got his son back safe and sound.’
But the older son became angry and refused to go in. His father came out and appealed to him, but he answered his father, ‘Look! These many years I have worked like a slave for you and I never disobeyed your commands. Yet you never gave me even a young goat so I could celebrate with my friends. But when this son of yours came back, who has devoured your assets with prostitutes, you killed the fattened calf for him!’
Then the father said to him, ‘Son, you are always with me, and everything that belongs to me is yours. It was appropriate to celebrate and be glad, for your brother was dead and is alive; he was lost and is found.’”
"""
new_revised_standard_version = """
Then Jesus said, “There was a man who had two sons. The younger of them said to his father, ‘Father, give me the share of the property that will belong to me.’ So he divided his property between them.
A few days later the younger son gathered all he had and traveled to a distant country, and there he squandered his property in dissolute living. When he had spent everything, a severe famine took place throughout that country, and he began to be in need. So he went and hired himself out to one of the citizens of that country, who sent him to his fields to feed pigs. He would gladly have filled himself with the pods that the pigs were eating; and no one gave him anything.
But when he came to himself he said, ‘How many of my father’s hired hands have bread enough and to spare, but here I am dying of hunger! I will get up and go to my father, and I will say to him, Father, I have sinned against heaven and before you; I am no longer worthy to be called your son; treat me like one of your hired hands.’ So he set off and went to his father.
But while he was still far off, his father saw him and was filled with compassion; he ran and put his arms around him and kissed him. Then the son said to him, ‘Father, I have sinned against heaven and before you; I am no longer worthy to be called your son.’
But the father said to his slaves, ‘Quickly, bring out a robe—the best one—and put it on him; put a ring on his finger and sandals on his feet. And get the fatted calf and kill it, and let us eat and celebrate; for this son of mine was dead and is alive again; he was lost and is found!’ And they began to celebrate.
Now his elder son was in the field; and when he came and approached the house, he heard music and dancing. He called one of the slaves and asked what was going on. He replied, ‘Your brother has come, and your father has killed the fatted calf, because he has got him back safe and sound.’
Then he became angry and refused to go in. His father came out and began to plead with him. But he answered his father, ‘Listen! For all these years I have been working like a slave for you, and I have never disobeyed your command; yet you have never given me even a young goat so that I might celebrate with my friends. But when this son of yours came back, who has devoured your property with prostitutes, you killed the fatted calf for him!’
Then the father said to him, ‘Son, you are always with me, and all that is mine is yours. But we had to celebrate and rejoice, because this brother of yours was dead and has come to life; he was lost and has been found.’”
"""

texts = [
    legacy_standard_bible,
    king_james_version,
    new_international_version,
    english_standard_version,
    new_living_translation,
    new_american_standard_bible,
    new_king_james_version,
    christian_standard_bible,
    new_english_translation,
    new_revised_standard_version
]